Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2021-04, with the labels that each got.

#1505 FieldSerializer: do not ignore final fields.
  jme3-networking/src/main/java/com/jme3/network/serializing/serializers/FieldSerializer.java
Labels: enhancement

#1492 Adds getters/setters for Camera field of view and aspect ratio
  jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
  jme3-core/src/main/java/com/jme3/renderer/Camera.java
  jme3-examples/src/main/java/jme3test/renderer/TestAspectFov.java
Labels: enhancement

#1494 Added JmeSurfaceView.java class , for embedding jme-game in a custom xml UI-design.
  jme3-android/build.gradle
  jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java
  jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnExceptionThrown.java
  jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/OnRendererCompleted.java
Labels: Android, enhancement

#1498 visible methods and fields shouldn't depend on invisible classes
  jme3-core/src/main/java/com/jme3/app/state/ConstantVerifierState.java
  jme3-core/src/main/java/com/jme3/font/BitmapFont.java
  jme3-core/src/main/java/com/jme3/input/JoystickCompatibilityMappings.java
  jme3-core/src/main/java/com/jme3/scene/instancing/InstancedNode.java
  jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java
  jme3-examples/src/main/java/jme3test/gui/TestBitmapFontLayout.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/material/FbxMaterialProperties.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: Spring Cleaning

#1502 cleanup of scene processors that don't implement profiling
  jme3-android/src/main/java/com/jme3/app/state/VideoRecorderAppState.java
  jme3-core/src/main/java/com/jme3/app/state/ScreenshotAppState.java
  jme3-core/src/main/java/com/jme3/post/HDRRenderer.java
  jme3-core/src/main/java/com/jme3/shadow/BasicShadowRenderer.java
  jme3-core/src/main/java/com/jme3/shadow/PssmShadowRenderer.java
  jme3-desktop/src/main/java/com/jme3/app/state/VideoRecorderAppState.java
  jme3-desktop/src/main/java/com/jme3/system/AWTFrameProcessor.java
  jme3-effects/src/main/java/com/jme3/water/ReflectionProcessor.java
  jme3-effects/src/main/java/com/jme3/water/SimpleWaterProcessor.java
  jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget.java
  jme3-examples/src/main/java/jme3test/post/TestRenderToMemory.java
Labels: Spring Cleaning

#1504 resolve issue #1499 (more constructors and methods for ArmatureMask)
  jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java
  jme3-core/src/test/java/com/jme3/anim/ArmatureMaskTest.java
Labels: enhancement

#1507 resolve #1453 (AnimationFactory should support the new system)
  jme3-core/src/main/java/com/jme3/anim/AnimFactory.java
  jme3-core/src/main/java/com/jme3/animation/AnimationFactory.java
  jme3-examples/src/main/java/jme3test/model/anim/TestAnimationFactory.java
Labels: enhancement

#1509 avoid accessing static fields through instance variables
  jme3-bullet/src/common/java/com/jme3/bullet/control/KinematicRagdollControl.java
  jme3-core/src/main/java/com/jme3/cinematic/events/AnimationEvent.java
  jme3-examples/src/main/java/jme3test/animation/TestCinematic.java
  jme3-examples/src/main/java/jme3test/helloworld/HelloInput.java
  jme3-examples/src/main/java/jme3test/input/TestCameraNode.java
  jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java
  jme3-examples/src/main/java/jme3test/input/TestJoystick.java
  jme3-examples/src/main/java/jme3test/post/TestDepthOfField.java
  jme3-examples/src/main/java/jme3test/water/TestPostWaterLake.java
Labels: Spring Cleaning

#1508 add a CinematicEvent for the new animation system
  jme3-core/src/main/java/com/jme3/cinematic/events/AnimEvent.java
  jme3-core/src/main/java/com/jme3/cinematic/events/AnimationEvent.java
  jme3-examples/src/main/java/jme3test/animation/TestCinematic.java
Labels: enhancement

#1510 delete deprecated setters that are currently no-ops
  jme3-core/src/main/java/com/jme3/animation/Bone.java
  jme3-core/src/main/java/com/jme3/light/LightProbe.java
  jme3-core/src/main/java/com/jme3/material/RenderState.java
  jme3-core/src/main/java/com/jme3/renderer/RenderContext.java
  jme3-core/src/main/java/com/jme3/scene/Mesh.java
  jme3-core/src/main/java/com/jme3/shadow/AbstractShadowFilter.java
  jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java
  jme3-core/src/main/java/com/jme3/texture/Image.java
  jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java
  jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowFilterVR.java
  jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java
Labels: Spring Cleaning

#1517 FXAA.frag: read alpha value from texture instead of passing constant 1
  jme3-effects/src/main/resources/Common/MatDefs/Post/FXAA.frag
Labels: enhancement

#1516 privatize package-private loggers
  jme3-core/src/main/java/com/jme3/anim/tween/Tweens.java
  jme3-core/src/main/java/com/jme3/app/state/BaseAppState.java
  jme3-core/src/main/java/com/jme3/app/state/ConstantVerifierState.java
  jme3-core/src/main/java/com/jme3/util/clone/Cloner.java
  jme3-networking/src/main/java/com/jme3/network/base/DefaultClient.java
  jme3-networking/src/main/java/com/jme3/network/base/DefaultServer.java
  jme3-networking/src/main/java/com/jme3/network/base/KernelAdapter.java
  jme3-networking/src/main/java/com/jme3/network/base/MessageListenerRegistry.java
  jme3-networking/src/main/java/com/jme3/network/kernel/AbstractKernel.java
  jme3-networking/src/main/java/com/jme3/network/kernel/tcp/SelectorKernel.java
  jme3-networking/src/main/java/com/jme3/network/kernel/udp/UdpKernel.java
  jme3-networking/src/main/java/com/jme3/network/message/SerializerRegistrationsMessage.java
  jme3-networking/src/main/java/com/jme3/network/serializing/serializers/FieldSerializer.java
  jme3-networking/src/main/java/com/jme3/network/service/AbstractHostedConnectionService.java
  jme3-networking/src/main/java/com/jme3/network/service/ServiceManager.java
  jme3-networking/src/main/java/com/jme3/network/service/rmi/RmiHostedService.java
  jme3-networking/src/main/java/com/jme3/network/service/rmi/RmiRegistry.java
  jme3-networking/src/main/java/com/jme3/network/service/rpc/RpcConnection.java
  jme3-networking/src/main/java/com/jme3/network/service/rpc/RpcHostedService.java
  jme3-networking/src/main/java/com/jme3/network/service/serializer/ClientSerializerRegistrationsService.java
  jme3-networking/src/main/java/com/jme3/network/util/AbstractMessageDelegator.java
  jme3-networking/src/main/java/com/jme3/network/util/SessionDataDelegator.java
Labels: Spring Cleaning

#1519 resolve javadoc warnings in the jme3-effects library
  jme3-effects/build.gradle
  jme3-effects/src/main/java/com/jme3/post/filters/BloomFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/CartoonEdgeFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/ColorOverlayFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/ComposeFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/CrossHatchFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/DepthOfFieldFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/FXAAFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/FadeFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/FogFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/GammaCorrectionFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/LightScatteringFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/PosterizationFilter.java
  jme3-effects/src/main/java/com/jme3/post/filters/RadialBlurFilter.java
  jme3-effects/src/main/java/com/jme3/post/ssao/SSAOFilter.java
  jme3-effects/src/main/java/com/jme3/water/ReflectionProcessor.java
  jme3-effects/src/main/java/com/jme3/water/SimpleWaterProcessor.java
  jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
Labels: Documentation, Spring Cleaning

#1521 jme3-core: add missing javadoc to the com.jme3.anim package
  jme3-core/src/main/java/com/jme3/anim/AnimClip.java
  jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
  jme3-core/src/main/java/com/jme3/anim/AnimTrack.java
  jme3-core/src/main/java/com/jme3/anim/AnimationMask.java
  jme3-core/src/main/java/com/jme3/anim/Armature.java
  jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java
  jme3-core/src/main/java/com/jme3/anim/Joint.java
  jme3-core/src/main/java/com/jme3/anim/MatrixJointModelTransform.java
  jme3-core/src/main/java/com/jme3/anim/MorphControl.java
  jme3-core/src/main/java/com/jme3/anim/MorphTrack.java
  jme3-core/src/main/java/com/jme3/anim/SkinningControl.java
  jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
  jme3-core/src/main/java/com/jme3/anim/util/JointModelTransform.java
Labels: Documentation, Spring Cleaning

#1522 resolve javadoc warnings in the jme3-jbullet library
  jme3-bullet/src/common/java/com/jme3/bullet/control/BetterCharacterControl.java
  jme3-bullet/src/common/java/com/jme3/bullet/control/CharacterControl.java
  jme3-bullet/src/common/java/com/jme3/bullet/util/CollisionShapeFactory.java
  jme3-jbullet/build.gradle
  jme3-jbullet/src/main/java/com/jme3/bullet/PhysicsSpace.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/PhysicsCollisionEvent.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/PhysicsCollisionObject.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CapsuleCollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/CompoundCollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/GImpactCollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/MeshCollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/collision/shapes/SphereCollisionShape.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/ConeJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/HingeJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/PhysicsJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/Point2PointJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/SixDofJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/joints/SliderJoint.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsCharacter.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsGhostObject.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsRigidBody.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsVehicle.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/VehicleWheel.java
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/infos/RigidBodyMotionState.java
  jme3-jbullet/src/main/java/com/jme3/bullet/util/DebugShapeFactory.java
Labels: Documentation, Spring Cleaning

#1523 deprecate com.jme3.anim.Weights
  jme3-core/src/main/java/com/jme3/anim/Weights.java
Labels: Spring Cleaning

#1527 GLRenderer: avoid NPE reported by Pavl_G
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
Labels: bug

#1530 address issue #1528 (distinguish ARM macOS/Windows from other platforms)
  jme3-core/src/main/java/com/jme3/system/JmeSystemDelegate.java
  jme3-core/src/main/java/com/jme3/system/Platform.java
Labels: enhancement
