Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2021-03, with the labels that each got.

#1476 TerrainQuad: serialize "patchSize" field.
  jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
  jme3-terrain/src/test/java/com/jme3/terrain/TestTerrainExporting.java
Labels: bug

#1475 Android native sound fix and update openal-soft to 1.21.1
  .github/workflows/main.yml
  jme3-android-native/openalsoft.gradle
  jme3-android-native/src/native/jme_decode/Android.mk
  jme3-android-native/src/native/jme_openalsoft/Android.mk
  jme3-android-native/src/native/jme_openalsoft/Application.mk
  jme3-android-native/src/native/jme_openalsoft/config.h
  jme3-android-native/src/native/jme_openalsoft/version.h
Labels: Android

#1481 resolve issue #1447 (no setter for EnvironmentCamera background color)
  jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
Labels: enhancement

#1451 testcase and fix for issue #1388 (Quaternion javadoc is misleading)
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/test/java/com/jme3/math/TestIssue1388.java
Labels: Documentation

#1482 resolve issue #1074 (Renderer lacks getters for sRGB properties)
  jme3-core/src/main/java/com/jme3/renderer/Renderer.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/main/java/com/jme3/system/NullRenderer.java
Labels: enhancement

#1485 AppStateManager profiler for render and post render
  jme3-core/src/main/java/com/jme3/app/state/AppStateManager.java
Labels: enhancement

#1463 Gltf unlit
  jme3-examples/src/main/java/jme3test/light/TestGltfUnlit.java
  jme3-examples/src/main/resources/jme3test/scenes/unlit.bin
  jme3-examples/src/main/resources/jme3test/scenes/unlit.blend
  jme3-examples/src/main/resources/jme3test/scenes/unlit.gltf
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitMaterialAdapter.java
  jme3-plugins/src/test/java/com/jme3/scene/plugins/gltf/GltfLoaderTest.java
Labels: enhancement

#1483 Joy axis update
  jme3-android/src/main/java/com/jme3/input/android/AndroidJoystickJoyInput14.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidSensorJoyInput.java
  jme3-core/src/main/java/com/jme3/input/JoystickCompatibilityMappings.java
  jme3-core/src/main/java/com/jme3/input/event/JoyAxisEvent.java
  jme3-lwjgl/src/main/java/com/jme3/input/lwjgl/JInputJoyInput.java
  jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwJoystickInput.java
Labels: enhancement

#1486 resolve issue #1419 (explicitly thrown NullPointerExceptions)
  jme3-core/src/main/java/com/jme3/material/Material.java
  jme3-core/src/main/java/com/jme3/scene/Geometry.java
  jme3-core/src/main/java/com/jme3/scene/Node.java
  jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java
  jme3-core/src/main/java/com/jme3/shadow/PssmShadowRenderer.java
  jme3-core/src/main/java/com/jme3/texture/Image.java
  jme3-core/src/plugins/java/com/jme3/asset/plugins/FileLocator.java
  jme3-desktop/src/main/java/com/jme3/app/SettingsDialog.java
  jme3-desktop/src/main/java/com/jme3/system/AWTComponentRenderer.java
  jme3-niftygui/src/main/java/com/jme3/niftygui/SoundHandleJme.java
  jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/LODGeomap.java
  jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
  jme3-vr/src/main/java/com/jme3/shadow/AbstractShadowRendererVR.java
Labels: Spring Cleaning

#1488 jme3-examples: delete 7 tests for issues specific to native Bullet
  jme3-examples/src/main/java/jme3test/bullet/TestIssue1029.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue1283.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue894.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue911.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue918.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue919.java
  jme3-examples/src/main/java/jme3test/bullet/TestIssue928.java
Labels: Physics

#1443 Added KHR_lights_punctual gltf extension
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/LightsPunctualExtensionLoader.java
  jme3-plugins/src/test/java/com/jme3/scene/plugins/gltf/GltfLoaderTest.java
  jme3-plugins/src/test/resources/gltf/lights/MODEL_ROUNDED_CUBE_PART_1/indices.bin
  jme3-plugins/src/test/resources/gltf/lights/MODEL_ROUNDED_CUBE_PART_1/normals.bin
  jme3-plugins/src/test/resources/gltf/lights/MODEL_ROUNDED_CUBE_PART_1/positions.bin
  jme3-plugins/src/test/resources/gltf/lights/lights.gltf
Labels: enhancement

#1489 Action: publicize the setLength() method
  jme3-core/src/main/java/com/jme3/anim/tween/action/Action.java
Labels: enhancement

#1490 resolve issue 1446 (test whether an EnvironmentCamera is busy)
  jme3-core/src/main/java/com/jme3/environment/EnvironmentCamera.java
  jme3-examples/src/main/java/jme3test/light/pbr/RefEnv.java
Labels: enhancement
