Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2021-11, with the labels that each got.

#1621 solve issue 1619 (add texture-compression formats)
  jme3-core/src/main/java/com/jme3/renderer/Caps.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLExt.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/main/java/com/jme3/texture/Image.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DDSLoader.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DXGIFormat.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java
  jme3-examples/src/main/java/jme3test/texture/dds/TestLoadDds.java
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC1_12.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC2_11.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC3_10.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC4_9.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC4_S_8.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC5_7.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC5_S_6.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC6H_3.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC6H_SF_2.DDS
  jme3-testdata/src/main/resources/Textures/dds/Monkey_PNG_BC7_1.DDS
Labels: enhancement

#1629 Support texture flipping for signed versions of RGTC 1 and 2
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java
Labels: enhancement

#1627 BufferedInputStream enhancement android
  jme3-android/src/main/java/com/jme3/texture/plugins/AndroidBufferImageLoader.java
  jme3-android/src/main/java/com/jme3/texture/plugins/AndroidNativeImageLoader.java
Labels: Android

#1646 jme3-core: solve 10 javadoc diagnostics from JDK 11
  jme3-core/src/main/java/checkers/quals/DefaultLocation.java
  jme3-core/src/main/java/com/jme3/bounding/BoundingSphere.java
  jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
  jme3-core/src/main/java/com/jme3/input/Input.java
  jme3-core/src/main/java/com/jme3/math/FastMath.java
Labels: Documentation

#1647 solve issue 1640 (CartoonEdgeFilter failing to override read() and write())
  jme3-effects/src/main/java/com/jme3/post/filters/CartoonEdgeFilter.java
  jme3-effects/src/test/java/com/jme3/post/filters/CartoonEdgeFilterTest.java
Labels: defect

#1651 solve issue 1648 (jme3-ios javadoc copyied from jme3-android)
  jme3-ios/src/main/java/com/jme3/input/ios/IosTouchHandler.java
  jme3-ios/src/main/java/com/jme3/input/ios/TouchEventPool.java
Labels: Documentation, iOS

#1643 solve issue 1555 (add API to determine max line width)
  jme3-android/src/main/java/com/jme3/renderer/android/AndroidGL.java
  jme3-core/src/main/java/com/jme3/renderer/Renderer.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GL.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/main/java/com/jme3/system/NullRenderer.java
  jme3-examples/src/main/java/jme3test/renderer/TestLineWidth.java
  jme3-ios/src/main/java/com/jme3/renderer/ios/IosGL.java
  jme3-ios/src/main/java/com/jme3/renderer/ios/JmeIosGLES.java
  jme3-lwjgl/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java
  jme3-lwjgl3/src/main/java/com/jme3/renderer/lwjgl/LwjglGL.java
Labels: enhancement

#1642 improve the TransformTrack javadoc
  jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
Labels: Documentation

#1660 Un-deprecate AndroidBufferImageLoader
  jme3-android/src/main/java/com/jme3/texture/plugins/AndroidBufferImageLoader.java
  jme3-android/src/main/java/com/jme3/texture/plugins/AndroidNativeImageLoader.java
  jme3-android/src/main/resources/com/jme3/asset/Android.cfg
Labels: Android

#1656 convert inner class Layer to a top-level class
  jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
  jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
Labels: enhancement

#1655 solve issue #1098 (preferred coding style isn't documented)
  CONTRIBUTING.md
Labels: Documentation

#1653 apply preferred style to com.jme3.renderer
  jme3-core/src/main/java/com/jme3/renderer/Camera.java
  jme3-core/src/main/java/com/jme3/renderer/Caps.java
  jme3-core/src/main/java/com/jme3/renderer/IDList.java
  jme3-core/src/main/java/com/jme3/renderer/Limits.java
  jme3-core/src/main/java/com/jme3/renderer/RenderContext.java
  jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
  jme3-core/src/main/java/com/jme3/renderer/Renderer.java
  jme3-core/src/main/java/com/jme3/renderer/RendererException.java
  jme3-core/src/main/java/com/jme3/renderer/Statistics.java
  jme3-core/src/main/java/com/jme3/renderer/ViewPort.java
Labels: Documentation

#1664 jme3-examples: simplify 6 unnecessary uses of unary minus
  jme3-examples/src/main/java/jme3test/bullet/TestAttachDriver.java
  jme3-examples/src/main/java/jme3test/bullet/TestFancyCar.java
  jme3-examples/src/main/java/jme3test/bullet/TestPhysicsCar.java
Labels: examples

#1671 CONTRIBUTING.md: add step-by-step instructions for submitting a PR
  CONTRIBUTING.md
Labels: Documentation

#1666 clarify and update the J3O format description
  jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java
Labels: Documentation

#1675 document the correct build procedure
  CONTRIBUTING.md
Labels: Documentation

#1670 Added Window Position for LJWGL3 libraries
  jme3-core/src/main/java/com/jme3/system/AppSettings.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Labels: enhancement
