Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2021-12, with the labels that each got.

#1684 CenterQuad: new class javadoc
  jme3-vr/src/main/java/com/jme3/scene/CenterQuad.java
Labels: Documentation

#1697 Fix issue #1687 (NPE in TestIssue1120)
  jme3-examples/src/main/java/jme3test/bullet/TestIssue1120.java
Labels: examples

#1689 new javadoc for Vector3f
  jme3-core/src/main/java/com/jme3/math/Vector3f.java
Labels: Documentation

#1665 ColorAdjustmentFilter
  jme3-effects/src/main/java/com/jme3/post/filters/ContrastAdjustmentFilter.java
  jme3-effects/src/main/resources/Common/MatDefs/Post/ContrastAdjustment.frag
  jme3-effects/src/main/resources/Common/MatDefs/Post/ContrastAdjustment.j3md
  jme3-effects/src/main/resources/Common/MatDefs/Post/ContrastAdjustment15.frag
  jme3-examples/src/main/java/jme3test/post/TestContrastAdjustment.java
  jme3-testdata/src/main/resources/Textures/Sky/Earth/Earth.jpg
Labels: enhancement

#1708 remove the local.properties file
  .gitignore
  local.properties
Labels: buildscript

#1706 new javadoc for Transform
  jme3-core/src/main/java/com/jme3/math/Transform.java
Labels: Documentation

#1625 Rework Test MultiRenderTarget to actually show how to use multiple
  jme3-examples/src/main/java/jme3test/post/TestMultiRenderTarget.java
  jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.frag
  jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.j3md
  jme3-examples/src/main/resources/TestMRT/MatDefs/ExtractRGB.vert
Labels: examples

#1701 New RectangleMesh shape class
  jme3-core/src/main/java/com/jme3/math/Rectangle.java
  jme3-core/src/main/java/com/jme3/scene/shape/RectangleMesh.java
  jme3-examples/src/main/java/jme3test/input/TestCameraNode.java
  jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java
  jme3-examples/src/main/java/jme3test/light/TestTransparentShadow.java
  jme3-examples/src/main/java/jme3test/material/TestParallax.java
  jme3-examples/src/main/java/jme3test/material/TestParallaxPBR.java
  jme3-examples/src/main/java/jme3test/post/TestTransparentCartoonEdge.java
  jme3-examples/src/main/java/jme3test/post/TestTransparentSSAO.java
  jme3-examples/src/main/java/jme3test/texture/TestAnisotropicFilter.java
  jme3-examples/src/main/java/jme3test/water/TestSceneWater.java
Labels: enhancement

#1711 jme3-lwjgl3: add a WindowSizeListener
  jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/WindowSizeListener.java
Labels: enhancement

#1712 clarify some non-javadoc comments
  jme3-android/src/main/java/com/jme3/input/android/AndroidGestureProcessor.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidJoystickJoyInput14.java
  jme3-android/src/main/java/com/jme3/input/android/AndroidTouchInput.java
  jme3-android/src/main/java/com/jme3/system/android/AndroidConfigChooser.java
  jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
  jme3-bullet/src/common/java/com/jme3/bullet/control/KinematicRagdollControl.java
  jme3-core/src/main/java/com/jme3/animation/AnimChannel.java
  jme3-core/src/main/java/com/jme3/app/state/AppStateManager.java
  jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java
  jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java
  jme3-core/src/main/java/com/jme3/font/BitmapFont.java
  jme3-core/src/main/java/com/jme3/input/ChaseCamera.java
  jme3-core/src/main/java/com/jme3/renderer/IDList.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/main/java/com/jme3/scene/BatchNode.java
  jme3-core/src/main/java/com/jme3/scene/shape/Cylinder.java
  jme3-core/src/main/java/com/jme3/shadow/AbstractShadowRenderer.java
  jme3-core/src/main/java/com/jme3/util/ListSort.java
  jme3-core/src/plugins/java/com/jme3/asset/plugins/HttpZipLocator.java
  jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/ktx/KTXLoader.java
  jme3-core/src/test/java/com/jme3/light/LightFilterTest.java
  jme3-core/src/tools/java/jme3tools/optimize/GeometryBatchFactory.java
  jme3-lwjgl/src/main/java/com/jme3/opencl/lwjgl/LwjglEvent.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglAbstractDisplay.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglCanvas.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
  jme3-networking/src/main/java/com/jme3/network/base/DefaultClient.java
  jme3-networking/src/main/java/com/jme3/network/base/DefaultServer.java
  jme3-networking/src/main/java/com/jme3/network/base/KernelAdapter.java
  jme3-networking/src/main/java/com/jme3/network/base/protocol/GreedyMessageBuffer.java
  jme3-networking/src/main/java/com/jme3/network/base/protocol/LazyMessageBuffer.java
  jme3-networking/src/main/java/com/jme3/network/service/rmi/ClassInfoRegistry.java
  jme3-niftygui/src/main/java/com/jme3/niftygui/InputSystemJme.java
  jme3-niftygui/src/main/java/com/jme3/niftygui/JmeBatchRenderBackend.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/main/java/com/jme3/material/plugin/export/materialdef/J3mdTechniqueDefWriter.java
  jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/SceneLoader.java
  jme3-vr/src/main/java/com/jme3/app/VRApplication.java
  jme3-vr/src/main/java/com/jme3/input/vr/AbstractVRViewManager.java
  jme3-vr/src/main/java/com/jme3/input/vr/oculus/OculusViewManager.java
  jme3-vr/src/main/java/com/jme3/input/vr/openvr/OpenVRViewManager.java
  jme3-vr/src/main/java/com/jme3/input/vr/osvr/OSVRViewManager.java
  jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglWindowVR.java
Labels: Documentation

#1722 LwjglWindow:assign new thread to `mainThread` field.
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Labels: bug
