Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2021-05, with the labels that each got.

#1534 fix issue #1533 (failed assertion in TestAnimMigration)
  jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureDebugAppState.java
Labels: bug

#1532 TransformTrack: add null checks to getTranslations() and getRotations()
  jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
Labels: bug

#1536 Joint: make 2 methods accessible to subclasses
  jme3-core/src/main/java/com/jme3/anim/Joint.java
Labels: enhancement

#1540 LodGenerator.java: improve the javadoc
  jme3-core/src/tools/java/jme3tools/optimize/LodGenerator.java
Labels: Documentation

#1537 AnimEvent: solve bug where onStop() kills prior event on the same layer
  jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
  jme3-core/src/main/java/com/jme3/cinematic/events/AnimEvent.java
  jme3-examples/src/main/java/jme3test/animation/TestJaime.java
Labels: bug

#1541 correct the dependencies of jme3-jbullet
  jme3-jbullet/build.gradle
  lib/jbullet.jar
  lib/stack-alloc.jar
Labels: Physics, buildscript

#1547 solve issue #1544 (diagnostic messages from TestMusicPlayer)
  jme3-examples/src/main/java/jme3test/audio/TestMusicPlayer.java
Labels: bug

#1549 test case and solution for issue #1548 (MorphControl doesn't override methods)
  jme3-core/src/main/java/com/jme3/anim/MorphControl.java
  jme3-examples/src/main/java/jme3test/model/anim/TestMorph.java
Labels: bug

#1550 Matrix4f: improve the javadoc
  jme3-core/src/main/java/com/jme3/math/Matrix4f.java
Labels: Documentation

#1565 Test and solution for issue #1564 (setting Material parameter of type IntArray)
  jme3-core/src/main/java/com/jme3/shader/Uniform.java
  jme3-core/src/test/java/com/jme3/shader/UniformTest.java
Labels: bug
