Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2022-01, with the labels that each got.

#1725 new javadoc for Quaternion
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
Labels: Documentation

#1726 fix and test for issue 1723 (more serialization bugs in RenderState)
  jme3-core/src/main/java/com/jme3/material/RenderState.java
  jme3-core/src/test/java/com/jme3/material/RenderStateTest.java
Labels: defect

#1707 Test post water 1699
  jme3-examples/src/main/java/jme3test/water/TestPostWater.java
Labels: examples

#1727 new javadoc for Matrix3f
  jme3-core/src/main/java/com/jme3/math/Matrix3f.java
Labels: Documentation

#1730 Fix NullPointerException in AnimLayer.update()
  jme3-core/src/main/java/com/jme3/anim/AnimLayer.java
Labels: bug

#1728 AlAudioRenderer: update OpenAL state when dry filter is re-applied
  jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java
Labels: bug

#1729 new javadoc for Vector2f
  jme3-core/src/main/java/com/jme3/math/Vector2f.java
Labels: Documentation

#1732 avoid self-closing HTML tags in javadoc
  jme3-examples/src/main/java/jme3test/renderer/TestBlendEquations.java
  jme3-jbullet/src/main/java/com/jme3/bullet/util/DebugShapeFactory.java
  jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQuery.java
  jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryInt.java
  jme3-lwjgl3/src/main/java/com/jme3/opencl/lwjgl/info/InfoQueryObject.java
Labels: Documentation

#1733 deal with unresolved references in javadoc
  jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java
  jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java
  jme3-core/src/main/java/com/jme3/material/Technique.java
Labels: Documentation

#1747 Configure circular deps as warning on eclipse
  common.gradle
Labels: buildscript

#1746 GlfwMouseInput: scale mouse coords only if Retina AppSetting is true
  jme3-lwjgl3/src/main/java/com/jme3/input/lwjgl/GlfwMouseInput.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Labels: bug

#1743 clarify comments and javadoc
  jme3-android/src/main/java/com/jme3/input/android/AndroidSensorJoyInput.java
  jme3-core/src/main/java/com/jme3/animation/AnimControl.java
  jme3-core/src/main/java/com/jme3/audio/AudioKey.java
  jme3-core/src/main/java/com/jme3/font/BitmapText.java
  jme3-core/src/main/java/com/jme3/font/Letters.java
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/main/java/com/jme3/math/Transform.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
  jme3-core/src/main/java/com/jme3/scene/VertexBuffer.java
  jme3-core/src/main/java/com/jme3/scene/control/CameraControl.java
  jme3-core/src/main/java/com/jme3/util/BufferUtils.java
  jme3-core/src/main/java/com/jme3/util/mikktspace/MikkTSpaceContext.java
  jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java
  jme3-examples/src/main/java/jme3test/light/TestLightControlDirectional.java
  jme3-examples/src/main/java/jme3test/light/TestLightControlSpot.java
  jme3-examples/src/main/java/jme3test/model/anim/TestAnimationFactory.java
  jme3-examples/src/main/java/jme3test/post/TestSSAO2.java
  jme3-examples/src/main/java/jme3test/stress/TestBatchLod.java
  jme3-examples/src/main/java/jme3test/stress/TestLodStress.java
  jme3-examples/src/main/java/jme3test/terrain/TerrainTestAndroid.java
  jme3-examples/src/main/java/jme3test/tools/TestSaveGame.java
  jme3-networking/src/main/java/com/jme3/network/kernel/udp/UdpKernel.java
  jme3-plugins/src/ogre/java/com/jme3/scene/plugins/ogre/MeshLoader.java
  jme3-terrain/src/main/java/com/jme3/terrain/heightmap/FaultHeightMap.java
  jme3-vr/src/main/java/com/jme3/app/VREnvironment.java
  jme3-vr/src/main/java/com/jme3/input/vr/AbstractVRMouseManager.java
Labels: Documentation

#1744 Add simple math methods to Vector3f
  jme3-core/src/main/java/com/jme3/math/Vector3f.java
Labels: enhancement

#1738 TerrainQuad: publicize fixNormals()
  jme3-terrain/src/main/java/com/jme3/terrain/geomipmap/TerrainQuad.java
Labels: enhancement

#1755 Add simple math methods to Vector4f
  jme3-core/src/main/java/com/jme3/math/Vector4f.java
Labels: enhancement

#1756 Add simple math methods to Vector2f
  jme3-core/src/main/java/com/jme3/math/Vector2f.java
Labels: enhancement

#1754 Fix issue 1705 (serialize 6 mesh subclasses)
  jme3-core/src/main/java/com/jme3/scene/debug/SkeletonInterBoneWire.java
  jme3-core/src/main/java/com/jme3/scene/debug/SkeletonPoints.java
  jme3-core/src/main/java/com/jme3/scene/debug/SkeletonWire.java
  jme3-core/src/main/java/com/jme3/scene/debug/custom/ArmatureInterJointsWire.java
  jme3-core/src/main/java/com/jme3/scene/shape/Surface.java
  jme3-core/src/test/java/com/jme3/scene/debug/TestCloneMesh.java
  jme3-vr/src/main/java/com/jme3/scene/CenterQuad.java
Labels: defect

#1762 solve issue #1761 (AssertionError in ALAudioRenderer)
  jme3-core/src/main/java/com/jme3/audio/openal/ALAudioRenderer.java
  jme3-examples/src/main/java/jme3test/audio/TestIssue1761.java
Labels: bug

#1757 Add set methods and constructors to ColorRGBA that take in a Vector param
  jme3-core/src/main/java/com/jme3/math/ColorRGBA.java
Labels: enhancement
