Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2022-02, with the labels that each got.

#1750 Separate concept of window size from default framebuffer size
  jme3-android/src/main/java/com/jme3/app/AndroidHarness.java
  jme3-android/src/main/java/com/jme3/app/AndroidHarnessFragment.java
  jme3-android/src/main/java/com/jme3/app/jmeSurfaceView/JmeSurfaceView.java
  jme3-core/src/main/java/com/jme3/app/LegacyApplication.java
  jme3-core/src/main/java/com/jme3/post/SceneProcessor.java
  jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
  jme3-core/src/main/java/com/jme3/system/AppSettings.java
  jme3-core/src/main/java/com/jme3/system/SystemListener.java
  jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
Labels: enhancement

#1763 PhysicsCharacter: add javadoc for the setGravity() method
  jme3-jbullet/src/main/java/com/jme3/bullet/objects/PhysicsCharacter.java
Labels: Documentation

#1758 Add FOR macro to GLSL preprocessor and J3MD
  jme3-core/src/plugins/java/com/jme3/material/plugins/J3MLoader.java
  jme3-core/src/plugins/java/com/jme3/shader/plugins/GLSLLoader.java
  jme3-core/src/test/java/com/jme3/shader/GLSLPreprocessorTest.java
  jme3-core/src/test/resources/GLSLPreprocessorTest.testFOR.validOutput
  jme3-core/src/tools/java/jme3tools/shader/Preprocessor.java
Labels: enhancement

#1765 JoyButtonTrigger: clarify that the constructor arg is not an axis ID
  jme3-core/src/main/java/com/jme3/input/controls/JoyButtonTrigger.java
Labels: Documentation

#1764 jme3-nifty should account for gamma correction
  jme3-examples/src/main/java/jme3test/animation/TestCinematic.java
  jme3-examples/src/main/java/jme3test/app/state/TestAppStates.java
  jme3-examples/src/main/java/jme3test/niftygui/TestIssue99.java
  jme3-examples/src/main/java/jme3test/niftygui/TestNiftyExamples.java
  jme3-examples/src/main/java/jme3test/niftygui/TestNiftyToMesh.java
  jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java
  jme3-niftygui/src/main/java/com/jme3/niftygui/RenderDeviceJme.java
Labels: defect

#1766 TestPostWater: avoid using the deprecated BitmapText constructor
  jme3-examples/src/main/java/jme3test/water/TestPostWater.java
Labels: examples

#1772 InstancedGeometry: added a field to keep track of all instance data b…
  jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
Labels: enhancement

#1770 AppSettings: solve 2 javadoc diagnostics
  jme3-core/src/main/java/com/jme3/system/AppSettings.java
Labels: Documentation

#1771 SimpleApplication: correct 2 typos in the javadoc
  jme3-core/src/main/java/com/jme3/app/SimpleApplication.java
Labels: Documentation
