Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2022-12, with the labels that each got.

#1819 JmeSurfaceView: Package migration
  jme3-android/src/main/java/com/jme3/view/package-info.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/JmeSurfaceView.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/OnExceptionThrown.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/OnLayoutDrawn.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/OnRendererCompleted.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/OnRendererStarted.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/package-info.java
Labels: Android

#1881 BlendableAction: Fix JavaDoc for setMaxTransitionWeight & replace assert with IllegalArgumentException
  jme3-core/src/main/java/com/jme3/anim/tween/action/BlendableAction.java
Labels: enhancement, Documentation

#1880 Fix #1412 (GltfLoader does not support AO packed in MetallicRoughnessMap)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: enhancement
