Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-01, with the labels that each got.

#1889 Fix #1773 (Wrong particle position when `worldSpace` flag equals to true)
  jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
  jme3-examples/src/main/java/jme3test/effect/TestIssue1773.java
Labels: bug

#1895 jme3-niftygui: solve issue #1891 (incorrect fullscreen layout)
  jme3-niftygui/src/main/java/com/jme3/niftygui/NiftyJmeDisplay.java
Labels: bug

#1898 Fix #1890 (crashes attempting to run example apps in fullscreen with LWJGL v2)
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java
Labels: bug

#1888 When in VR attach the debug scene to the two eye's scenes. Fix #1795
  jme3-jbullet/build.gradle
  jme3-jbullet/src/main/java/com/jme3/bullet/debug/BulletDebugAppState.java
  jme3-vr/src/main/java/com/jme3/app/VRAppState.java
Labels: bug

#1901 Refactored PBR Terrain to use new for-loops. Fix #1785
  jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag
Labels: bug

#1899 add the Spatial.addControlAt() method
  jme3-core/src/main/java/com/jme3/scene/Spatial.java
  jme3-core/src/test/java/com/jme3/scene/SpatialTest.java
Labels: enhancement

#1894 JmeContext: add a getSystemListener() method
  jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
  jme3-core/src/main/java/com/jme3/system/JmeContext.java
  jme3-core/src/main/java/com/jme3/system/NullContext.java
  jme3-desktop/src/main/java/com/jme3/system/AWTContext.java
  jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java
  jme3-ios/src/main/java/com/jme3/system/ios/IGLESContext.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
Labels: enhancement

#1912 ParticleEmitter: improve code readability. Apply the DRY principle
  jme3-core/src/main/java/com/jme3/effect/ParticleEmitter.java
Labels: enhancement

#1911 add 4 getters to JmeContext for screen position and frame-buffer size
  jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
  jme3-core/src/main/java/com/jme3/system/JmeContext.java
  jme3-core/src/main/java/com/jme3/system/NullContext.java
  jme3-desktop/src/main/java/com/jme3/system/AWTContext.java
  jme3-desktop/src/main/java/com/jme3/system/awt/AwtPanelsContext.java
  jme3-ios/src/main/java/com/jme3/system/ios/IGLESContext.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-lwjgl3/src/main/java/com/jme3/system/lwjgl/LwjglWindow.java
  jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglWindowVR.java
Labels: enhancement

#1910 test and fix for #1909 (NPE while generating tangents)
  jme3-core/src/main/java/com/jme3/util/mikktspace/MikkTSpaceImpl.java
  jme3-core/src/test/java/com/jme3/util/TestIssue1909.java
Labels: bug

#1914 jme3-lwjgl: bump to lwjgl 2.9.5
  jme3-lwjgl/build.gradle
Labels: bug

#1918 Fix #1917 (RendererException in ScreenshotAppState: Attempting to upload empty buffer)
  jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
Labels: bug

#1921 PBRLighting: fix comment describing packed MetallicRoughnessMap
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
Labels: Documentation

#1922 main.yml: deploy with jdk17
  .github/workflows/main.yml
Labels: buildscript

#1924 Fix #1923 (OSSRH artifacts are build with different java version)
  .github/workflows/main.yml
Labels: buildscript

#1929 solve issue #1928 (OutOfMemoryError in FBX importer)
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxFile.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/file/FbxReader.java
Labels: bug

#1931 solve issue #1930 (NPE in FbxLayerElement)
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/mesh/FbxLayerElement.java
Labels: bug

#1934 solve issue #1932 (class cast exceptions in FBX importer)
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxBindPose.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxCluster.java
Labels: defect

#1936 solve issue #1933 (unsupported operation in FbxNode)
  jme3-core/src/main/java/com/jme3/math/Matrix4f.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/node/FbxNode.java
Labels: defect

#1938 solve issue #1937 (NPE in FbxObject)
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/FbxLoader.java
Labels: defect
