Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-03, with the labels that each got.

#1976 solve issue #1975: TestAttachDriver doesn't reset properly
  jme3-examples/src/main/java/jme3test/bullet/TestAttachDriver.java
Labels: Physics, examples

#1973 Improve NativeLibraryLoader
  jme3-desktop/src/main/java/com/jme3/system/JmeDesktopSystem.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibraries.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibrary.java
  jme3-desktop/src/main/java/com/jme3/system/NativeLibraryLoader.java
  jme3-examples/src/main/java/jme3test/audio/TestMusicPlayer.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-vr/src/main/java/com/jme3/system/lwjgl/LwjglContextVR.java
Labels: enhancement

#1983 Deploy master branch commits as snapshot
  .github/workflows/main.yml
  common.gradle
Labels: buildscript

#1979 Allow use of Emissive color as a multiplier with EmissiveMap in PBRLighting
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
Labels: enhancement

#1980 Add support for NormalScale in PBRLighting & GltfLoader
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/MaterialAdapter.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Labels: enhancement

#1981 Add support for AoStrength in PBRLighting & GltfLoader
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.j3md
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Labels: enhancement

#1986 Some javadoc cleanup
  jme3-android/src/main/java/com/jme3/audio/plugins/NativeVorbisFile.java
  jme3-vr/src/main/java/com/jme3/input/vr/VRInputAPI.java
Labels: Documentation

#1988 LwjglContext: re-initialize renderer on context restart (lwjgl 2)
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglContext.java
  jme3-lwjgl/src/main/java/com/jme3/system/lwjgl/LwjglDisplay.java
Labels: bug
