Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-05, with the labels that each got.

#2005 solve issue #2003 (ParticleDepositionHeightMap.load return value)
  jme3-terrain/src/main/java/com/jme3/terrain/heightmap/ParticleDepositionHeightMap.java
Labels: defect

#2006 solve issue #2002 (TerrainGridTileLoaderTest fails to load tiles)
  jme3-examples/src/main/java/jme3test/terrain/TerrainGridTileLoaderTest.java
Labels: defect, examples

#1993 solve issue #1992: better messages in spatial assertions
  jme3-core/src/main/java/com/jme3/scene/Spatial.java
Labels: enhancement

#2016 solve issue #2015 (Picture class lacks 2 getters)
  jme3-core/src/main/java/com/jme3/ui/Picture.java
Labels: enhancement

#2018 CloneableSmartAsset: clarify the setKey() javadoc
  jme3-core/src/main/java/com/jme3/asset/CloneableSmartAsset.java
Labels: Documentation
