Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-06, with the labels that each got.

#2024 solve issue #2023 (getRotationColumn() returns wrong result)
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/test/java/com/jme3/light/LightFilterTest.java
  jme3-core/src/test/java/com/jme3/math/TestIssue2023.java
Labels: bug

#2026 jme3-core: document a few places where normalization is assumed
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/main/java/com/jme3/math/Transform.java
  jme3-core/src/main/java/com/jme3/scene/Spatial.java
Labels: Documentation

#2029 By default use PrimitiveAllocator on Android
  jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
Labels: Android

#2035 solve issue 2034 (serialization of ShaderNodeDefinition)
  jme3-core/src/main/java/com/jme3/shader/ShaderNodeDefinition.java
Labels: bug
