Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-08, with the labels that each got.

#2042 1877: Add checkstyle to project
  common.gradle
  config/checkstyle/checkstyle-suppressions.xml
  config/checkstyle/checkstyle.xml
  jme3-vr/build.gradle
Labels: buildscript

#2058 Fix issue #2056 . Check for NaN uniforms
  jme3-core/src/main/java/com/jme3/light/PointLight.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
Labels: bug, enhancement

#2067 Autoformat workflow
  .github/workflows/format.yml
Labels: buildscript

#2064 Update build.gradle to use default Build Tools (30.0.2) required by A…
  jme3-android-examples/build.gradle
Labels: Android, buildscript
