Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-11, with the labels that each got.

#2138 Solve #2136 (flow-control issue with glTF alpha parameter)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Labels: bug

#2106 Add userdata loader to gltf
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfModelKey.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UserDataLoader.java
Labels: enhancement

#2140 Fix sign of tbn generator that caused normal map flipping in some situations
  jme3-core/src/main/java/com/jme3/util/mikktspace/MikktspaceTangentGenerator.java
  jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.frag
  jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.j3md
  jme3-core/src/main/resources/Common/MatDefs/Light/PBRLighting.frag
  jme3-core/src/main/resources/Common/MatDefs/Light/SPLighting.frag
  jme3-examples/src/main/java/jme3test/material/TestNormalMappingConsistency.java
  jme3-examples/src/main/resources/jme3test/normalmapCompare/NormalTangentMirrorTest.gltf
  jme3-examples/src/main/resources/jme3test/normalmapCompare/NormalTangentMirrorTest_BaseColor.png
  jme3-examples/src/main/resources/jme3test/normalmapCompare/NormalTangentTest_Normal.png
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/Image_0.png
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/Image_1.png
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/Image_2.png
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/Material.001.material
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/NormalTangentMirrorTest.scene
  jme3-examples/src/main/resources/jme3test/normalmapCompare/ogre/NormalTangentTest_low.mesh.xml
Labels: defect

#2137 Read bytes more efficiently
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java
Labels: enhancement

#2147 solve issue #2135 (ClassCastException in MTLLoader)
  jme3-core/src/plugins/java/com/jme3/scene/plugins/MTLLoader.java
Labels: bug

#2148 solve issue #2131 (NPE while loading a GLB v1 asset)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GlbLoader.java
Labels: defect
