Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-07, with the labels that each got.

#2038 Application#stop(boolean): fix javadoc args issue
  jme3-core/src/main/java/com/jme3/app/Application.java
  jme3-core/src/main/java/com/jme3/app/LegacyApplication.java
Labels: Documentation

#2044 1977: Fix AppSettings samples javadoc
  jme3-core/src/main/java/com/jme3/system/AppSettings.java
Labels: Documentation

#2041 Issue 1011: Make JmeExport save consistent in its path handling
  jme3-core/src/main/java/com/jme3/export/JmeExporter.java
  jme3-core/src/plugins/java/com/jme3/export/binary/BinaryExporter.java
  jme3-plugins/src/main/java/com/jme3/material/plugin/export/material/J3MExporter.java
  jme3-plugins/src/test/java/com/jme3/export/JmeExporterTest.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLExporter.java
Labels: defect

#2053 solve issue #2045 (ArmatureMask.createMask() duplicate code)
  jme3-core/src/main/java/com/jme3/anim/ArmatureMask.java
Labels: enhancement
