Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-12, with the labels that each got.

#2151 updates to the README
  README.md
Labels: Documentation

#2155 solve issue #2076 (software skinning requires vertex normals)
  jme3-core/src/main/java/com/jme3/anim/SkinningControl.java
  jme3-core/src/main/java/com/jme3/animation/SkeletonControl.java
  jme3-examples/src/main/java/jme3test/animation/TestIssue2076.java
Labels: defect

#2152 jme3-core: add 2 getters for frame interpolators
  jme3-core/src/main/java/com/jme3/anim/MorphTrack.java
  jme3-core/src/main/java/com/jme3/anim/TransformTrack.java
Labels: enhancement

#2160 Fix javadoc errors
  jme3-core/src/main/java/com/jme3/material/RenderState.java
  jme3-core/src/main/java/com/jme3/scene/instancing/InstancedGeometry.java
  jme3-core/src/main/java/com/jme3/util/res/ResourceLoader.java
  jme3-core/src/main/java/com/jme3/util/res/Resources.java
  jme3-examples/src/main/java/jme3test/animation/TestIssue2076.java
Labels: Documentation

#2157 solve issue #2096 (error launching examples from the dist jar)
  jme3-examples/build.gradle
Labels: defect

#2163 Fixes Gltf Emissive Intensity Default
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/MaterialAdapter.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitMaterialAdapter.java
Labels: defect

#2165 solve issue #2164 (setCausticsTexture() sets non-existent parameter)
  jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
Labels: bug

#2172 solve issue #2168 (incomplete serialization of FXAAFilter)
  jme3-effects/src/main/java/com/jme3/post/filters/FXAAFilter.java
  jme3-effects/src/test/java/com/jme3/post/filters/FXAAFilterTest.java
Labels: defect

#2171 solve issue #2167 (incomplete serialization of PosterizationFilter) #2170
  jme3-effects/src/main/java/com/jme3/post/filters/PosterizationFilter.java
  jme3-effects/src/test/java/com/jme3/post/filters/PosterizationFilterTest.java
Labels: defect

#2170 solve issue #2166 (logic error in DepthOfFieldFilter serialization)
  jme3-effects/src/main/java/com/jme3/post/filters/DepthOfFieldFilter.java
  jme3-effects/src/test/java/com/jme3/post/filters/DepthOfFieldFilterTest.java
Labels: defect

#2156 document issue #2089 (scale factors assumed positive)
  jme3-core/src/main/java/com/jme3/math/Matrix4f.java
  jme3-core/src/main/java/com/jme3/math/Quaternion.java
  jme3-core/src/main/java/com/jme3/math/Transform.java
Labels: Documentation
