Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-10, with the labels that each got.

#2075 GltfLoader: copyedits to 18 inline comments
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: Documentation

#2079 bugfix: IllegalArgumentException in Camera.setFov() (issue #2078)
  jme3-core/src/main/java/com/jme3/input/FlyByCamera.java
Labels: bug

#2088 Fixes Issue #2085 (KHR_materials_emissive_strengh extension)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBREmissiveStrengthExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBREmissiveStrengthMaterialAdapter.java
Labels: defect

#2102 Improve GL Debug
  jme3-core/src/main/java/com/jme3/post/Filter.java
  jme3-core/src/main/java/com/jme3/post/FilterPostProcessor.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLRenderer.java
Labels: enhancement

#2100 Disable shadows for sky
  jme3-core/src/main/java/com/jme3/util/SkyFactory.java
Labels: bug

#2093 Fixes XML Map Export
  jme3-core/src/main/java/com/jme3/export/FormatVersion.java
  jme3-core/src/main/java/com/jme3/scene/UserData.java
  jme3-examples/src/main/java/jme3test/export/TestIssue2068.java
  jme3-plugins/src/test/java/com/jme3/export/JmeExporterTest.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLUtils.java
Labels: bug

#2094 build using Gradle v7.6.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: buildscript

#2103 Fix Gltf imported spatial names
  jme3-examples/src/main/java/jme3test/model/TestGltfNaming.java
  jme3-examples/src/main/resources/jme3test/gltfnaming/multi.bin
  jme3-examples/src/main/resources/jme3test/gltfnaming/multi.gltf
  jme3-examples/src/main/resources/jme3test/gltfnaming/parent.bin
  jme3-examples/src/main/resources/jme3test/gltfnaming/parent.gltf
  jme3-examples/src/main/resources/jme3test/gltfnaming/single.bin
  jme3-examples/src/main/resources/jme3test/gltfnaming/single.gltf
  jme3-examples/src/main/resources/jme3test/gltfnaming/untitled.bin
  jme3-examples/src/main/resources/jme3test/gltfnaming/untitled.gltf
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: defect

#2104 Fix Gltf cache leak
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: bug

#2080 SceneGraphIterator
  jme3-core/src/main/java/com/jme3/scene/SceneGraphIterator.java
  jme3-examples/src/main/java/jme3test/scene/TestSceneIteration.java
Labels: enhancement, hacktoberfest-accepted

#2086 Fixes Issue #2083 (enable vertex colors in glTF loader)
  jme3-examples/src/main/java/jme3test/model/TestGltfVertexColor.java
  jme3-examples/src/main/resources/jme3test/gltfvertexcolor/VertexColorTest.glb
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: defect, hacktoberfest-accepted

#2091 Partial fix for Issue #2087 (NegativeScaleTest)
  jme3-core/src/main/java/com/jme3/material/Material.java
  jme3-core/src/main/java/com/jme3/material/RenderState.java
  jme3-examples/src/main/java/jme3test/model/TestGltfLoading.java
Labels: defect, hacktoberfest-accepted

#2116 Increase MAX_DEFINES in DefineList (re-do)
  jme3-core/src/main/java/com/jme3/material/TechniqueDef.java
  jme3-core/src/main/java/com/jme3/shader/DefineList.java
  jme3-core/src/test/java/com/jme3/renderer/OpaqueComparatorTest.java
  jme3-core/src/test/java/com/jme3/shader/DefineListTest.java
Labels: enhancement

#2113 Geometry constructor with material.
  jme3-core/src/main/java/com/jme3/scene/Geometry.java
Labels: enhancement, hacktoberfest-accepted

#2081 Fixes Issue #2070 (AssetKey overrides)
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/AnimationList.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/SceneKey.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfModelKey.java
Labels: defect, hacktoberfest-accepted

#2084 Fixes Issue #2082 (AlphaBlendModeTest)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRMaterialAdapter.java
Labels: defect, hacktoberfest-accepted

#2126 add debug groups for shadow draw calls
  jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
  jme3-core/src/main/java/com/jme3/renderer/queue/RenderQueue.java
Labels: enhancement, hacktoberfest-accepted

#2130 Fix RenderState Parameters Leaking Between Renders
  jme3-core/src/main/java/com/jme3/material/Material.java
  jme3-core/src/main/java/com/jme3/material/RenderState.java
  jme3-examples/src/main/java/jme3test/light/TestSpotLightShadows.java
Labels: bug, hacktoberfest-accepted

#2128 Solve issue #2127 (excessive memory use while loading GLB)
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
Labels: defect, hacktoberfest-accepted

#2134 Fixes Issue #2132 (Texture.load() doesn't trigger mipmap generation)
  jme3-core/src/main/java/com/jme3/texture/Texture.java
Labels: defect
