Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2023-02, with the labels that each got.

#1940 solve issue #1939 [NPE in FbxMesh.applyCluster()]
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/FbxLoader.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxCluster.java
  jme3-plugins/src/fbx/java/com/jme3/scene/plugins/fbx/anim/FbxToJmeTrack.java
Labels: bug

#1947 Update Application.start javadoc
  jme3-core/src/main/java/com/jme3/app/Application.java
Labels: Documentation

#1948 Update RenderState.setLineWidth javadoc
  jme3-core/src/main/java/com/jme3/material/RenderState.java
Labels: Documentation

#1951 Add WaterFilter.getReflectionView method
  jme3-effects/src/main/java/com/jme3/water/WaterFilter.java
Labels: enhancement

#1961 solve issue #1960 (use jme3-jogg for loading ogg files on android)
  jme3-android/src/main/resources/com/jme3/asset/Android.cfg
Labels: Android
