Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2024-05, with the labels that each got.

#2251 solution for issue #2250 (exceptions from Image.setMultiSamples(1))
  jme3-core/src/main/java/com/jme3/texture/Image.java
  jme3-core/src/test/java/com/jme3/texture/TestIssue2250.java
Labels: defect

#2257 main.yml: upgrade the wrapper validation action to v3
  .github/workflows/main.yml
Labels: buildscript

#2253 override toString() in certain math classes
  jme3-core/src/main/java/com/jme3/math/AbstractTriangle.java
  jme3-core/src/main/java/com/jme3/math/Line.java
  jme3-core/src/main/java/com/jme3/math/LineSegment.java
  jme3-core/src/main/java/com/jme3/math/Rectangle.java
  jme3-core/src/test/java/com/jme3/math/TestToString.java
Labels: enhancement

#2229 Added SoftBloomFilter
  jme3-effects/src/main/java/com/jme3/post/filters/SoftBloomFilter.java
  jme3-effects/src/main/resources/Common/MatDefs/Post/Downsample.frag
  jme3-effects/src/main/resources/Common/MatDefs/Post/Downsample.j3md
  jme3-effects/src/main/resources/Common/MatDefs/Post/SoftBloomFinal.frag
  jme3-effects/src/main/resources/Common/MatDefs/Post/SoftBloomFinal.j3md
  jme3-effects/src/main/resources/Common/MatDefs/Post/Upsample.frag
  jme3-effects/src/main/resources/Common/MatDefs/Post/Upsample.j3md
  jme3-examples/src/main/java/jme3test/post/TestBloom.java
  jme3-examples/src/main/java/jme3test/post/TestSoftBloom.java
Labels: enhancement
