Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2024-06, with the labels that each got.

#2274 Fix Casting error that occurred on certain GPUs
  jme3-terrain/src/main/resources/Common/MatDefs/Terrain/AdvancedPBRTerrain.frag
  jme3-terrain/src/main/resources/Common/MatDefs/Terrain/PBRTerrain.frag
Labels: bug

#2252 implement equals(), hashCode(), and isSimilar() for bounding volumes
  jme3-core/src/main/java/com/jme3/bounding/BoundingBox.java
  jme3-core/src/main/java/com/jme3/bounding/BoundingSphere.java
  jme3-core/src/main/java/com/jme3/bounding/BoundingVolume.java
  jme3-core/src/test/java/com/jme3/bounding/TestBoundingBox.java
  jme3-core/src/test/java/com/jme3/bounding/TestBoundingSphere.java
Labels: enhancement

#2278 partial revert of PR #2060 (JSON parser abstraction)
  jme3-examples/build.gradle
  jme3-plugins/build.gradle
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/CustomContentManager.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/ExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/ExtrasLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/GltfUtils.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/LightsPunctualExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBREmissiveStrengthExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/PBRSpecGlossExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/TextureTransformExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UnlitExtensionLoader.java
  jme3-plugins/src/gltf/java/com/jme3/scene/plugins/gltf/UserDataLoader.java
Labels: defect

#2283 test and fix for issue #2282 (VerifyError while creating AXIS_SWEEP_3 space)
  jme3-examples/src/main/java/jme3test/bullet/TestIssue2282.java
  jme3-jbullet/build.gradle
Labels: bug, Physics
