Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2024-01, with the labels that each got.

#2183 update the "gson" library to v2.10.1
  jme3-plugins-json-gson/build.gradle
Labels: buildscript

#2182 update copyright years in the license
  LICENSE.md
Labels: Documentation

#2181 solve issue #2178 (PBRTerrainTest typo)
  jme3-examples/src/main/java/jme3test/terrain/PBRTerrainTest.java
Labels: examples

#2180 solve issue #2177 (PBRTerrainAdvancedTest typo)
  jme3-examples/src/main/java/jme3test/terrain/PBRTerrainAdvancedTest.java
Labels: examples

#2101 Expand support for GL ES / WebGL compatible formats.
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLExt.java
  jme3-core/src/main/java/com/jme3/renderer/opengl/GLImageFormats.java
  jme3-core/src/main/java/com/jme3/texture/Image.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DDSLoader.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/DXTFlipper.java
  jme3-core/src/plugins/java/com/jme3/texture/plugins/ETCFlipper.java
Labels: enhancement

#2019 com.jme3.anim.tween.action.Action: basic javadoc
  jme3-core/src/main/java/com/jme3/anim/tween/action/Action.java
Labels: Documentation

#2043 Adds SingleLayerInfluenceMask
  jme3-core/src/main/java/com/jme3/anim/SingleLayerInfluenceMask.java
Labels: enhancement

#1165 Accelerated env baking on the GPU
  jme3-core/src/main/java/com/jme3/environment/EnvironmentProbeControl.java
  jme3-core/src/main/java/com/jme3/environment/FastLightProbeFactory.java
  jme3-core/src/main/java/com/jme3/environment/baker/EnvBaker.java
  jme3-core/src/main/java/com/jme3/environment/baker/GenericEnvBaker.java
  jme3-core/src/main/java/com/jme3/environment/baker/IBLEnvBaker.java
  jme3-core/src/main/java/com/jme3/environment/baker/IBLEnvBakerLight.java
  jme3-core/src/main/java/com/jme3/environment/baker/IBLGLEnvBaker.java
  jme3-core/src/main/java/com/jme3/environment/baker/IBLGLEnvBakerLight.java
  jme3-core/src/main/java/com/jme3/environment/baker/IBLHybridEnvBakerLight.java
  jme3-core/src/main/java/com/jme3/renderer/RenderManager.java
  jme3-core/src/main/resources/Common/IBL/IBLKernels.frag
  jme3-core/src/main/resources/Common/IBL/IBLKernels.j3md
  jme3-core/src/main/resources/Common/IBL/IBLKernels.vert
  jme3-core/src/main/resources/Common/IBL/Math.glsl
  jme3-core/src/main/resources/Common/IBLSphH/IBLSphH.frag
  jme3-core/src/main/resources/Common/IBLSphH/IBLSphH.j3md
  jme3-core/src/main/resources/Common/IBLSphH/IBLSphH.vert
  jme3-examples/src/main/java/jme3test/light/pbr/TestPBRLighting.java
  jme3-examples/src/main/java/jme3test/light/pbr/TestPBRSimple.java
Labels: enhancement

#2020 com.jme3.anim.tween.action.BaseAction: basic javadoc
  jme3-core/src/main/java/com/jme3/anim/tween/action/BaseAction.java
Labels: Documentation
