Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2024-10, with the labels that each got.

#2319 update the groovy-test library to v3.0.22
  gradle/libs.versions.toml
Labels: buildscript

#2313 Fix for XMLExporter issues in #2310
  jme3-plugins/src/test/java/com/jme3/export/InputOutputCapsuleTest.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/DOMInputCapsule.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/DOMOutputCapsule.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/DOMSerializer.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLExporter.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLImporter.java
  jme3-plugins/src/xml/java/com/jme3/export/xml/XMLUtils.java
Labels: defect

#2322 update README.md to report 3.7 as the latest stable version
  README.md
Labels: Documentation

#2315 Armature.java: javadoc correction (to solve issue #2142 again)
  jme3-core/src/main/java/com/jme3/anim/Armature.java
Labels: Documentation

#2318 update j-ogg-vorbis to v1.0.6
  gradle/libs.versions.toml
Labels: buildscript

#2231 AnimComposer: return AnimLayer on the makeLayer and removeLayer methods.
  jme3-core/src/main/java/com/jme3/anim/AnimComposer.java
Labels: enhancement

#2324 add build instructions to the README (see issue #2308)
  README.md
Labels: Documentation
