Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2024-03, with the labels that each got.

#2208 Fix render states merging when additionalState is not set
  jme3-core/src/main/java/com/jme3/material/Material.java
  jme3-core/src/main/java/com/jme3/material/RenderState.java
Labels: bug

#2210 Fix divide by 0 in shadow utils for some scenes #2209
  jme3-core/src/main/java/com/jme3/shadow/ShadowUtil.java
Labels: bug

#2212 update Groovy to v3.0.21
  common.gradle
Labels: buildscript

#2213 don't code the Gradle version in build.gradle
  build.gradle
Labels: buildscript

#2214 jme3-examples: add the TestIssue2209 class
  jme3-examples/src/main/java/jme3test/light/TestIssue2209.java
Labels: enhancement, examples
