Repository jMonkeyEngine/jmonkeyengine, pull requests merged in 2025-02, with the labels that each got.

#2347 LICENSE.md: add 2025 to the copyright years
  LICENSE.md
Labels: Documentation

#2359 [Android] Fix Android JmeSurfaceView Memory Leak
  jme3-android/src/main/java/com/jme3/system/android/OGLESContext.java
  jme3-android/src/main/java/com/jme3/view/surfaceview/JmeSurfaceView.java
Labels: Android

#2364 Fix Fog in Lighting.frag
  jme3-core/src/main/resources/Common/MatDefs/Light/Lighting.frag
  jme3-core/src/main/resources/Common/ShaderLib/MaterialFog.glsllib
Labels: bug

#2022 com.jme3.anim.tween.action.BlendSpace: basic javadoc
  jme3-core/src/main/java/com/jme3/anim/tween/action/BlendSpace.java
Labels: Documentation
